// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	repository "github.com/joshsoftware/code-curiosity-2025/internal/repository"
	mock "github.com/stretchr/testify/mock"

	sqlx "github.com/jmoiron/sqlx"
)

// BadgeRepository is an autogenerated mock type for the BadgeRepository type
type BadgeRepository struct {
	mock.Mock
}

// BeginTx provides a mock function with given fields: ctx
func (_m *BadgeRepository) BeginTx(ctx context.Context) (*sqlx.Tx, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 *sqlx.Tx
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*sqlx.Tx, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *sqlx.Tx); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqlx.Tx)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CommitTx provides a mock function with given fields: tx
func (_m *BadgeRepository) CommitTx(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for CommitTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBadgeDetailsOfUser provides a mock function with given fields: ctx, tx, userId
func (_m *BadgeRepository) GetBadgeDetailsOfUser(ctx context.Context, tx *sqlx.Tx, userId int) ([]repository.Badge, error) {
	ret := _m.Called(ctx, tx, userId)

	if len(ret) == 0 {
		panic("no return value specified for GetBadgeDetailsOfUser")
	}

	var r0 []repository.Badge
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) ([]repository.Badge, error)); ok {
		return rf(ctx, tx, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, int) []repository.Badge); ok {
		r0 = rf(ctx, tx, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]repository.Badge)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *sqlx.Tx, int) error); ok {
		r1 = rf(ctx, tx, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandleTransaction provides a mock function with given fields: ctx, tx, incomingErr
func (_m *BadgeRepository) HandleTransaction(ctx context.Context, tx *sqlx.Tx, incomingErr error) error {
	ret := _m.Called(ctx, tx, incomingErr)

	if len(ret) == 0 {
		panic("no return value specified for HandleTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *sqlx.Tx, error) error); ok {
		r0 = rf(ctx, tx, incomingErr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RollbackTx provides a mock function with given fields: tx
func (_m *BadgeRepository) RollbackTx(tx *sqlx.Tx) error {
	ret := _m.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for RollbackTx")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*sqlx.Tx) error); ok {
		r0 = rf(tx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewBadgeRepository creates a new instance of BadgeRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBadgeRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *BadgeRepository {
	mock := &BadgeRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
