export const LOGGED_IN_USER_QUERY_KEY = "logged-in-user";
export const USER_BADGES_QUERY_KEY = "user-badges";
export const LEADERBOARD_QUERY_KEY = "leaderboard";
export const CURRENT_USER_RANK_QUERY_KEY = "current-user-rank";
export const RECENT_ACTIVITIES_QUERY_KEY = "recent-activities";
export const OVERVIEW_QUERY_KEY = "overview";
export const REPOSITORIES_KEY = "repositories";
export const REPOSITORY_KEY = "repository";
export const REPOSITORY_CONTRIBUTORS_QUERY_KEY = "repository-contributors";
export const REPOSITORY_LANGUAGES_QUERY_KEY = "repository-languages";
export const REPOSITORY_ACTIVITIES_QUERY_KEY = "repository-activites";
export const USER_ACTIVE_GOAL_LEVEL_QUERY_KEY = "user-goal-level";
export const GOAL_LEVELS_QUERY_KEY = "goal-levels";
export const USER_GOAL_LEVEL_PROGRESS_QUERY_KEY = "goal-level-progresss";
export const CONTRIBUTION_TYPES_QUERY_KEY = "contribution-types";
export const GITHUB_OAUTH_LOGIN_QUERY_KEY = "github-oauth-login";
export const USER_GOAL_LEVEL_UPDATE_QUERY_KEY = "user-goal-level-update";
export const USER_GOAL_LEVEL_SUMMARY_QUERY_KEY="user-goal-level-summary"

export const GET_ALL_USERS_QUERY_KEY = "get-all-users";